server:
  port: 8002

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.huade.pojo

# spring
spring:
  application:
    name: exam-provider-basic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/online_exam?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
